/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pos/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PairingController_pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pos/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pos/catalog/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pos/catalog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pos/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CatalogController_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pos/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PairDeviceDto: {
            /** @description The pairing code shown in the admin dashboard */
            pairingCode: string;
        };
        PairingResult: {
            token: string;
            accountId: number;
            accountName: string;
            locationId: number;
            locationName: string;
            deviceName: string;
        };
        PosCatalogBrand: {
            id: number;
            name: string;
        };
        PosCatalogCategory: {
            id: number;
            name: string;
        };
        PosCatalogImage: {
            id: number;
            url: string;
            position: number;
        };
        PosCatalogOptionValue: {
            optionName: string;
            value: string;
        };
        PosCatalogVariant: {
            id: number;
            sku: string | null;
            barcodes: string[];
            priceCents: number;
            stock: number;
            optionValues: components["schemas"]["PosCatalogOptionValue"][];
            imageUrl: string | null;
        };
        PosCatalogProduct: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["PosCatalogBrand"] | null;
            categories: components["schemas"]["PosCatalogCategory"][];
            images: components["schemas"]["PosCatalogImage"][];
            variants: components["schemas"]["PosCatalogVariant"][];
        };
        PosCatalogPage: {
            items: components["schemas"]["PosCatalogProduct"][];
            nextCursor: string | null;
            syncedAt: string;
        };
        PosScanResult: {
            product: components["schemas"]["PosCatalogProduct"];
            variantId: number;
        };
        PosSession: {
            accountId: number;
            accountName: string;
            locationId: number;
            locationName: string;
            deviceName: string;
        };
        CreateOrderItemDto: {
            variantId: number;
            quantity: number;
        };
        CreateOrderPaymentDto: {
            /** @enum {string} */
            method: "cash" | "card";
            amountTenderedCents?: number;
        };
        CreateOrderDto: {
            items: components["schemas"]["CreateOrderItemDto"][];
            payment: components["schemas"]["CreateOrderPaymentDto"];
        };
        PosOrderItem: {
            id: number;
            variantId: number | null;
            productName: string;
            sku: string | null;
            optionsLabel: string | null;
            priceCents: number;
            quantity: number;
            lineCents: number;
        };
        PosOrder: {
            id: number;
            /** @enum {string} */
            channel: "pos";
            subtotalCents: number;
            taxCents: number;
            totalCents: number;
            /** @enum {string} */
            paymentMethod: "cash" | "card";
            amountTenderedCents: number | null;
            changeCents: number | null;
            createdAt: string;
            items: components["schemas"]["PosOrderItem"][];
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                type: "invalid_request_error" | "authentication_error" | "permission_error" | "rate_limit_error" | "api_error";
                /** @enum {string} */
                code: "bad_request" | "unauthenticated" | "forbidden" | "not_found" | "method_not_allowed" | "not_acceptable" | "request_timeout" | "conflict" | "gone" | "precondition_failed" | "content_too_large" | "unsupported_media_type" | "misdirected_request" | "unprocessable_content" | "rate_limited" | "internal_error" | "not_implemented" | "bad_gateway" | "service_unavailable" | "gateway_timeout" | "http_version_not_supported" | "validation_failed" | "invalid_access_token" | "invalid_app_key" | "invalid_device_token" | "invalid_credentials" | "mfa_factor_required" | "email_taken";
                /** @description For people. Never parse it; branch on `code`. */
                message: string;
                /** @description The request field that caused the error. */
                param?: string;
                /** Format: uri */
                doc_url: string;
                /** @description The x-request-id of the request; quote it when reporting a problem. */
                request_id: string | null;
                /** @description Extra data for the code; its shape per code is in ErrorDetailsByCode. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Each error code's `details` shape, keyed by code. A code that isn't listed has no fixed shape. */
        ErrorDetailsByCode: {
            validation_failed: {
                /** @description Every failing field; nested properties as dotted paths. */
                fields: {
                    param: string;
                    message: string;
                }[];
            };
            /** @description up or down per health check. */
            service_unavailable?: {
                [key: string]: "up" | "down";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PairingController_pair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairDeviceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CatalogController_list: {
        parameters: {
            query?: {
                /** @description Match product name, variant SKU, or barcode */
                search?: string;
                limit?: number;
                /** @description nextCursor from the previous page */
                cursor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosCatalogPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CatalogController_scan: {
        parameters: {
            query: {
                /** @description A scanned barcode or a variant SKU */
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosScanResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CatalogController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosCatalogProduct"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CatalogController_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosSession"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosOrder"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
