/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as JoinRouteImport } from './routes/join'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as App403RouteImport } from './routes/app/403'
import { Route as AppProductsRouteRouteImport } from './routes/app/products/route'
import { Route as AppRolesRouteRouteImport } from './routes/app/roles/route'
import { Route as AppCartsIndexRouteImport } from './routes/app/carts/index'
import { Route as AppCartsIdRouteImport } from './routes/app/carts/$id'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as AppDevelopersIndexRouteImport } from './routes/app/developers/index'
import { Route as AppFailedOrdersIndexRouteImport } from './routes/app/failed-orders/index'
import { Route as AppInventoryIndexRouteImport } from './routes/app/inventory/index'
import { Route as AppInventoryMovementsRouteImport } from './routes/app/inventory/movements'
import { Route as AppLocationsIndexRouteImport } from './routes/app/locations/index'
import { Route as AppLocationsCreateRouteImport } from './routes/app/locations/create'
import { Route as AppOrdersIndexRouteImport } from './routes/app/orders/index'
import { Route as AppOrdersIdRouteImport } from './routes/app/orders/$id'
import { Route as AppPaymentsIndexRouteImport } from './routes/app/payments/index'
import { Route as AppPosDevicesIndexRouteImport } from './routes/app/pos-devices/index'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppProductsIdRouteImport } from './routes/app/products/$id'
import { Route as AppProductsCreateRouteImport } from './routes/app/products/create'
import { Route as AppRolesIndexRouteImport } from './routes/app/roles/index'
import { Route as AppRolesIdRouteImport } from './routes/app/roles/$id'
import { Route as AppRolesCreateRouteImport } from './routes/app/roles/create'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppUsersIndexRouteImport } from './routes/app/users/index'
import { Route as AppUsersIdRouteImport } from './routes/app/users/$id'
import { Route as AppUsersCreateRouteImport } from './routes/app/users/create'
import { Route as AppProductsBrandsIndexRouteImport } from './routes/app/products/brands/index'
import { Route as AppProductsBrandsCreateRouteImport } from './routes/app/products/brands/create'
import { Route as AppProductsCategoriesIndexRouteImport } from './routes/app/products/categories/index'
import { Route as AppProductsCategoriesCreateRouteImport } from './routes/app/products/categories/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const App403Route = App403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRouteRoute = AppRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCartsIndexRoute = AppCartsIndexRouteImport.update({
  id: '/carts/',
  path: '/carts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCartsIdRoute = AppCartsIdRouteImport.update({
  id: '/carts/$id',
  path: '/carts/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevelopersIndexRoute = AppDevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFailedOrdersIndexRoute = AppFailedOrdersIndexRouteImport.update({
  id: '/failed-orders/',
  path: '/failed-orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/inventory/movements',
  path: '/inventory/movements',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationsCreateRoute = AppLocationsCreateRouteImport.update({
  id: '/locations/create',
  path: '/locations/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosDevicesIndexRoute = AppPosDevicesIndexRouteImport.update({
  id: '/pos-devices/',
  path: '/pos-devices/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsCreateRoute = AppProductsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRolesRouteRoute,
} as any)
const AppRolesIdRoute = AppRolesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRolesRouteRoute,
} as any)
const AppRolesCreateRoute = AppRolesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRolesRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersCreateRoute = AppUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsBrandsIndexRoute = AppProductsBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsBrandsCreateRoute = AppProductsBrandsCreateRouteImport.update({
  id: '/brands/create',
  path: '/brands/create',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsCategoriesIndexRoute =
  AppProductsCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)
const AppProductsCategoriesCreateRoute =
  AppProductsCategoriesCreateRouteImport.update({
    id: '/categories/create',
    path: '/categories/create',
    getParentRoute: () => AppProductsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/app/roles': typeof AppRolesRouteRouteWithChildren
  '/app/403': typeof App403Route
  '/app/': typeof AppIndexRoute
  '/app/carts/$id': typeof AppCartsIdRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/locations/create': typeof AppLocationsCreateRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/roles/$id': typeof AppRolesIdRoute
  '/app/roles/create': typeof AppRolesCreateRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/users/create': typeof AppUsersCreateRoute
  '/app/carts/': typeof AppCartsIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/developers/': typeof AppDevelopersIndexRoute
  '/app/failed-orders/': typeof AppFailedOrdersIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/pos-devices/': typeof AppPosDevicesIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/products/brands/create': typeof AppProductsBrandsCreateRoute
  '/app/products/categories/create': typeof AppProductsCategoriesCreateRoute
  '/app/products/brands/': typeof AppProductsBrandsIndexRoute
  '/app/products/categories/': typeof AppProductsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/403': typeof App403Route
  '/app': typeof AppIndexRoute
  '/app/carts/$id': typeof AppCartsIdRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/locations/create': typeof AppLocationsCreateRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/roles/$id': typeof AppRolesIdRoute
  '/app/roles/create': typeof AppRolesCreateRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/users/create': typeof AppUsersCreateRoute
  '/app/carts': typeof AppCartsIndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/developers': typeof AppDevelopersIndexRoute
  '/app/failed-orders': typeof AppFailedOrdersIndexRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/locations': typeof AppLocationsIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/payments': typeof AppPaymentsIndexRoute
  '/app/pos-devices': typeof AppPosDevicesIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/roles': typeof AppRolesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/products/brands/create': typeof AppProductsBrandsCreateRoute
  '/app/products/categories/create': typeof AppProductsCategoriesCreateRoute
  '/app/products/brands': typeof AppProductsBrandsIndexRoute
  '/app/products/categories': typeof AppProductsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/products': typeof AppProductsRouteRouteWithChildren
  '/app/roles': typeof AppRolesRouteRouteWithChildren
  '/app/403': typeof App403Route
  '/app/': typeof AppIndexRoute
  '/app/carts/$id': typeof AppCartsIdRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/locations/create': typeof AppLocationsCreateRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/products/create': typeof AppProductsCreateRoute
  '/app/roles/$id': typeof AppRolesIdRoute
  '/app/roles/create': typeof AppRolesCreateRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/users/create': typeof AppUsersCreateRoute
  '/app/carts/': typeof AppCartsIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/developers/': typeof AppDevelopersIndexRoute
  '/app/failed-orders/': typeof AppFailedOrdersIndexRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/pos-devices/': typeof AppPosDevicesIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/roles/': typeof AppRolesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/products/brands/create': typeof AppProductsBrandsCreateRoute
  '/app/products/categories/create': typeof AppProductsCategoriesCreateRoute
  '/app/products/brands/': typeof AppProductsBrandsIndexRoute
  '/app/products/categories/': typeof AppProductsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/join'
    | '/signin'
    | '/signup'
    | '/app/products'
    | '/app/roles'
    | '/app/403'
    | '/app/'
    | '/app/carts/$id'
    | '/app/inventory/movements'
    | '/app/locations/create'
    | '/app/orders/$id'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/roles/$id'
    | '/app/roles/create'
    | '/app/users/$id'
    | '/app/users/create'
    | '/app/carts/'
    | '/app/customers/'
    | '/app/developers/'
    | '/app/failed-orders/'
    | '/app/inventory/'
    | '/app/locations/'
    | '/app/orders/'
    | '/app/payments/'
    | '/app/pos-devices/'
    | '/app/products/'
    | '/app/roles/'
    | '/app/settings/'
    | '/app/users/'
    | '/app/products/brands/create'
    | '/app/products/categories/create'
    | '/app/products/brands/'
    | '/app/products/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/signin'
    | '/signup'
    | '/app/403'
    | '/app'
    | '/app/carts/$id'
    | '/app/inventory/movements'
    | '/app/locations/create'
    | '/app/orders/$id'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/roles/$id'
    | '/app/roles/create'
    | '/app/users/$id'
    | '/app/users/create'
    | '/app/carts'
    | '/app/customers'
    | '/app/developers'
    | '/app/failed-orders'
    | '/app/inventory'
    | '/app/locations'
    | '/app/orders'
    | '/app/payments'
    | '/app/pos-devices'
    | '/app/products'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/products/brands/create'
    | '/app/products/categories/create'
    | '/app/products/brands'
    | '/app/products/categories'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/join'
    | '/signin'
    | '/signup'
    | '/app/products'
    | '/app/roles'
    | '/app/403'
    | '/app/'
    | '/app/carts/$id'
    | '/app/inventory/movements'
    | '/app/locations/create'
    | '/app/orders/$id'
    | '/app/products/$id'
    | '/app/products/create'
    | '/app/roles/$id'
    | '/app/roles/create'
    | '/app/users/$id'
    | '/app/users/create'
    | '/app/carts/'
    | '/app/customers/'
    | '/app/developers/'
    | '/app/failed-orders/'
    | '/app/inventory/'
    | '/app/locations/'
    | '/app/orders/'
    | '/app/payments/'
    | '/app/pos-devices/'
    | '/app/products/'
    | '/app/roles/'
    | '/app/settings/'
    | '/app/users/'
    | '/app/products/brands/create'
    | '/app/products/categories/create'
    | '/app/products/brands/'
    | '/app/products/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/403': {
      id: '/app/403'
      path: '/403'
      fullPath: '/app/403'
      preLoaderRoute: typeof App403RouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/carts/': {
      id: '/app/carts/'
      path: '/carts'
      fullPath: '/app/carts/'
      preLoaderRoute: typeof AppCartsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/carts/$id': {
      id: '/app/carts/$id'
      path: '/carts/$id'
      fullPath: '/app/carts/$id'
      preLoaderRoute: typeof AppCartsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/developers/': {
      id: '/app/developers/'
      path: '/developers'
      fullPath: '/app/developers/'
      preLoaderRoute: typeof AppDevelopersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/failed-orders/': {
      id: '/app/failed-orders/'
      path: '/failed-orders'
      fullPath: '/app/failed-orders/'
      preLoaderRoute: typeof AppFailedOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/inventory/movements': {
      id: '/app/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/app/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/locations/': {
      id: '/app/locations/'
      path: '/locations'
      fullPath: '/app/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/locations/create': {
      id: '/app/locations/create'
      path: '/locations/create'
      fullPath: '/app/locations/create'
      preLoaderRoute: typeof AppLocationsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payments/': {
      id: '/app/payments/'
      path: '/payments'
      fullPath: '/app/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pos-devices/': {
      id: '/app/pos-devices/'
      path: '/pos-devices'
      fullPath: '/app/pos-devices/'
      preLoaderRoute: typeof AppPosDevicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/$id': {
      id: '/app/products/$id'
      path: '/$id'
      fullPath: '/app/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/create': {
      id: '/app/products/create'
      path: '/create'
      fullPath: '/app/products/create'
      preLoaderRoute: typeof AppProductsCreateRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/roles/': {
      id: '/app/roles/'
      path: '/'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRolesRouteRoute
    }
    '/app/roles/$id': {
      id: '/app/roles/$id'
      path: '/$id'
      fullPath: '/app/roles/$id'
      preLoaderRoute: typeof AppRolesIdRouteImport
      parentRoute: typeof AppRolesRouteRoute
    }
    '/app/roles/create': {
      id: '/app/roles/create'
      path: '/create'
      fullPath: '/app/roles/create'
      preLoaderRoute: typeof AppRolesCreateRouteImport
      parentRoute: typeof AppRolesRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/$id': {
      id: '/app/users/$id'
      path: '/users/$id'
      fullPath: '/app/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users/create': {
      id: '/app/users/create'
      path: '/users/create'
      fullPath: '/app/users/create'
      preLoaderRoute: typeof AppUsersCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/brands/': {
      id: '/app/products/brands/'
      path: '/brands'
      fullPath: '/app/products/brands/'
      preLoaderRoute: typeof AppProductsBrandsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/brands/create': {
      id: '/app/products/brands/create'
      path: '/brands/create'
      fullPath: '/app/products/brands/create'
      preLoaderRoute: typeof AppProductsBrandsCreateRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/categories/': {
      id: '/app/products/categories/'
      path: '/categories'
      fullPath: '/app/products/categories/'
      preLoaderRoute: typeof AppProductsCategoriesIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/app/products/categories/create': {
      id: '/app/products/categories/create'
      path: '/categories/create'
      fullPath: '/app/products/categories/create'
      preLoaderRoute: typeof AppProductsCategoriesCreateRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
  }
}

interface AppProductsRouteRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsCreateRoute: typeof AppProductsCreateRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsBrandsCreateRoute: typeof AppProductsBrandsCreateRoute
  AppProductsCategoriesCreateRoute: typeof AppProductsCategoriesCreateRoute
  AppProductsBrandsIndexRoute: typeof AppProductsBrandsIndexRoute
  AppProductsCategoriesIndexRoute: typeof AppProductsCategoriesIndexRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsCreateRoute: AppProductsCreateRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsBrandsCreateRoute: AppProductsBrandsCreateRoute,
  AppProductsCategoriesCreateRoute: AppProductsCategoriesCreateRoute,
  AppProductsBrandsIndexRoute: AppProductsBrandsIndexRoute,
  AppProductsCategoriesIndexRoute: AppProductsCategoriesIndexRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppRolesRouteRouteChildren {
  AppRolesIdRoute: typeof AppRolesIdRoute
  AppRolesCreateRoute: typeof AppRolesCreateRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
}

const AppRolesRouteRouteChildren: AppRolesRouteRouteChildren = {
  AppRolesIdRoute: AppRolesIdRoute,
  AppRolesCreateRoute: AppRolesCreateRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
}

const AppRolesRouteRouteWithChildren = AppRolesRouteRoute._addFileChildren(
  AppRolesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppRolesRouteRoute: typeof AppRolesRouteRouteWithChildren
  App403Route: typeof App403Route
  AppIndexRoute: typeof AppIndexRoute
  AppCartsIdRoute: typeof AppCartsIdRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppLocationsCreateRoute: typeof AppLocationsCreateRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppUsersIdRoute: typeof AppUsersIdRoute
  AppUsersCreateRoute: typeof AppUsersCreateRoute
  AppCartsIndexRoute: typeof AppCartsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDevelopersIndexRoute: typeof AppDevelopersIndexRoute
  AppFailedOrdersIndexRoute: typeof AppFailedOrdersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppPosDevicesIndexRoute: typeof AppPosDevicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppRolesRouteRoute: AppRolesRouteRouteWithChildren,
  App403Route: App403Route,
  AppIndexRoute: AppIndexRoute,
  AppCartsIdRoute: AppCartsIdRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppLocationsCreateRoute: AppLocationsCreateRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppUsersIdRoute: AppUsersIdRoute,
  AppUsersCreateRoute: AppUsersCreateRoute,
  AppCartsIndexRoute: AppCartsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDevelopersIndexRoute: AppDevelopersIndexRoute,
  AppFailedOrdersIndexRoute: AppFailedOrdersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppPosDevicesIndexRoute: AppPosDevicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
