import createClient, { type Client, type Middleware } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import type { DoFn } from "./http.js";
export { ApiError } from "./http.js";
import { createProductsResource } from "./resources/products.js";
import { createBrandsResource } from "./resources/brands.js";
import { createCategoriesResource } from "./resources/categories.js";
import { createLocationsResource } from "./resources/locations.js";
import { createInventoryResource } from "./resources/inventory.js";
import { createApiKeysResource } from "./resources/api-keys.js";
import { createCartsResource } from "./resources/carts.js";
import { createStripeConnectResource } from "./resources/stripe-connect.js";
import { createOrdersResource } from "./resources/orders.js";
import { createFailedOrdersResource } from "./resources/failed-orders.js";
import { createFulfillmentsResource } from "./resources/fulfillments.js";
import { createAccountResource } from "./resources/account.js";
import { createUsersResource } from "./resources/users.js";
import { createCustomersResource } from "./resources/customers.js";
import { createDashboardResource } from "./resources/dashboard.js";
import { createRolesResource } from "./resources/roles.js";
import { createPermissionsResource } from "./resources/permissions.js";
import { createPosDevicesResource } from "./resources/pos-devices.js";

export type ApiKey = components["schemas"]["ApiKeyDto"];
export type CartListItem = components["schemas"]["CartListItem"];
export type CartDetail = components["schemas"]["CartDetail"];
export type PaginatedCarts = components["schemas"]["PaginatedCarts"];
export type Product = components["schemas"]["Product"];
export type PaginatedProducts = components["schemas"]["PaginatedProducts"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductVariant = components["schemas"]["ProductVariant"];
export type ProductOption = components["schemas"]["ProductOption"];
export type ProductImage = components["schemas"]["ProductImage"];
export type GetImageUploadUrlDto =
  components["schemas"]["GetImageUploadUrlDto"];
export type CreateVariantsDto = components["schemas"]["CreateVariantsDto"];
export type Brand = components["schemas"]["Brand"];
export type PaginatedBrands = components["schemas"]["PaginatedBrands"];
export type Category = components["schemas"]["Category"];
export type PaginatedCategories = components["schemas"]["PaginatedCategories"];
export type Location = components["schemas"]["Location"];
export type PaginatedLocations = components["schemas"]["PaginatedLocations"];
export type InventoryRecord = components["schemas"]["InventoryRecord"];
export type PaginatedInventory = components["schemas"]["PaginatedInventory"];
export type InventoryMovementRecord =
  components["schemas"]["InventoryMovementRecord"];
export type PaginatedInventoryMovements =
  components["schemas"]["PaginatedInventoryMovements"];
export type StripeConnectStatus = components["schemas"]["StripeConnectStatus"];
export type OrderListItem = components["schemas"]["OrderListItem"];
export type OrderDetail = components["schemas"]["OrderDetail"];
export type OrderDetailItem = components["schemas"]["OrderDetailItem"];
export type OrderShippingInfo = components["schemas"]["OrderShippingInfo"];
export type OrderPayment = components["schemas"]["OrderPayment"];
export type OrderEvent = components["schemas"]["OrderEvent"];
export type OrderStatusChange = components["schemas"]["OrderStatusChange"];
export type UpdateOrderStatusDto =
  components["schemas"]["UpdateOrderStatusDto"];
export type OrderRefund = components["schemas"]["OrderRefund"];
export type RefundOrderDto = components["schemas"]["RefundOrderDto"];
export type RefundLineDto = components["schemas"]["RefundLineDto"];
export type OrderCancellation = components["schemas"]["OrderCancellation"];
export type CancelOrderDto = components["schemas"]["CancelOrderDto"];
export type OrderItemAllocation = components["schemas"]["OrderItemAllocation"];
export type Fulfillment = components["schemas"]["Fulfillment"];
export type FulfillmentItem = components["schemas"]["FulfillmentItem"];
export type ShippingRate = components["schemas"]["ShippingRate"];
export type PaginatedOrders = components["schemas"]["PaginatedOrders"];
export type FailedOrder = components["schemas"]["FailedOrder"];
export type FailedOrdersList = components["schemas"]["FailedOrdersList"];
export type Account = components["schemas"]["Account"];
export type User = components["schemas"]["User"];
export type PaginatedUsers = components["schemas"]["PaginatedUsers"];
export type CreateUserDto = components["schemas"]["CreateUserDto"];
export type Customer = components["schemas"]["Customer"];
export type PaginatedCustomers = components["schemas"]["PaginatedCustomers"];
export type AcceptInviteDto = components["schemas"]["AcceptInviteDto"];
export type DashboardSummary = components["schemas"]["DashboardSummary"];
export type Permission = components["schemas"]["Permission"];
export type Role = components["schemas"]["Role"];
export type RoleDetail = components["schemas"]["RoleDetail"];
export type CreateRoleDto = components["schemas"]["CreateRoleDto"];
export type UpdateRoleDto = components["schemas"]["UpdateRoleDto"];
export type PosDevice = components["schemas"]["PosDevice"];
export type PosDevicePairing = components["schemas"]["PosDevicePairing"];
export type CreatePosDeviceDto = components["schemas"]["CreatePosDeviceDto"];
export type UpdatePosDeviceDto = components["schemas"]["UpdatePosDeviceDto"];

export class AdminClient {
  accessToken: string | undefined;
  client: Client<paths>;

  products: ReturnType<typeof createProductsResource>;
  brands: ReturnType<typeof createBrandsResource>;
  categories: ReturnType<typeof createCategoriesResource>;
  locations: ReturnType<typeof createLocationsResource>;
  inventory: ReturnType<typeof createInventoryResource>;
  apiKeys: ReturnType<typeof createApiKeysResource>;
  carts: ReturnType<typeof createCartsResource>;
  stripeConnect: ReturnType<typeof createStripeConnectResource>;
  orders: ReturnType<typeof createOrdersResource>;
  failedOrders: ReturnType<typeof createFailedOrdersResource>;
  fulfillments: ReturnType<typeof createFulfillmentsResource>;
  account: ReturnType<typeof createAccountResource>;
  users: ReturnType<typeof createUsersResource>;
  customers: ReturnType<typeof createCustomersResource>;
  dashboard: ReturnType<typeof createDashboardResource>;
  roles: ReturnType<typeof createRolesResource>;
  permissions: ReturnType<typeof createPermissionsResource>;
  posDevices: ReturnType<typeof createPosDevicesResource>;

  // every request needs the bearer token and the cross-origin cookie
  // (for the refresh_token) — centralized here instead of at each call site.
  // Request.headers is mutable in place, but credentials isn't, so that part
  // has to go through a rebuilt Request.
  private authMiddleware: Middleware = {
    onRequest: ({ request }) => {
      request.headers.set("Authorization", `Bearer ${this.accessToken}`);
      return new Request(request, { credentials: "include" });
    },
  };

  constructor(baseUrl: string) {
    this.client = createClient({ baseUrl });
    this.client.use(this.authMiddleware);

    const doRequest: DoFn = (request) => this.do(request);

    this.products = createProductsResource(this.client, doRequest);
    this.brands = createBrandsResource(this.client, doRequest);
    this.categories = createCategoriesResource(this.client, doRequest);
    this.locations = createLocationsResource(this.client, doRequest);
    this.inventory = createInventoryResource(this.client, doRequest);
    this.apiKeys = createApiKeysResource(this.client, doRequest);
    this.carts = createCartsResource(this.client, doRequest);
    this.stripeConnect = createStripeConnectResource(this.client, doRequest);
    this.orders = createOrdersResource(this.client, doRequest);
    this.failedOrders = createFailedOrdersResource(this.client, doRequest);
    this.fulfillments = createFulfillmentsResource(this.client, doRequest);
    this.account = createAccountResource(this.client, doRequest);
    this.users = createUsersResource(this.client, doRequest);
    this.customers = createCustomersResource(this.client, doRequest);
    this.dashboard = createDashboardResource(this.client, doRequest);
    this.roles = createRolesResource(this.client, doRequest);
    this.permissions = createPermissionsResource(this.client, doRequest);
    this.posDevices = createPosDevicesResource(this.client, doRequest);
  }

  async signIn(credentials: components["schemas"]["SignInDto"]) {
    const { data } = await this.client.POST("/auth/signin", {
      body: credentials,
    });

    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  async signUp(signup: components["schemas"]["SignUpDto"]) {
    const { data } = await this.client.POST("/auth/signup", {
      body: signup,
    });

    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  async acceptInvite(params: components["schemas"]["AcceptInviteDto"]) {
    const { data } = await this.client.POST("/auth/accept-invite", {
      body: params,
    });

    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  async refreshAccessToken() {
    const { data } = await this.client.GET("/auth/token/refresh");
    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  // clears the httpOnly refresh_token cookie server-side — the client can't
  // delete it itself — then drops the in-memory access token
  async logout() {
    await this.client.POST("/auth/logout");
    this.accessToken = undefined;
  }

  // request is a thunk so the retry rebuilds headers off the refreshed accessToken, not a stale one
  private async do<T>(
    request: () => Promise<{ data?: T; error?: unknown; response: Response }>,
  ) {
    const result = await request();
    if (result.response.status === 401) {
      await this.refreshAccessToken();
      return await request();
    }
    return result;
  }
}
