import createClient, { type Client, type Middleware } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import { ApiError, readErrorBody, unwrap, type DoFn } from "./http.js";
export { ApiError } from "./http.js";
import { createProductsResource } from "./resources/products.js";
import { createBrandsResource } from "./resources/brands.js";
import { createCategoriesResource } from "./resources/categories.js";
import { createLocationsResource } from "./resources/locations.js";
import { createInventoryResource } from "./resources/inventory.js";
import { createApiKeysResource } from "./resources/api-keys.js";
import { createCartsResource } from "./resources/carts.js";
import { createStripeConnectResource } from "./resources/stripe-connect.js";
import { createOrdersResource } from "./resources/orders.js";
import { createFailedOrdersResource } from "./resources/failed-orders.js";
import { createFulfillmentsResource } from "./resources/fulfillments.js";
import { createAccountResource } from "./resources/account.js";
import { createUsersResource } from "./resources/users.js";
import { createCustomersResource } from "./resources/customers.js";
import { createDashboardResource } from "./resources/dashboard.js";
import { createOnboardingResource } from "./resources/onboarding.js";
import { createRolesResource } from "./resources/roles.js";
import { createPermissionsResource } from "./resources/permissions.js";
import { createPosDevicesResource } from "./resources/pos-devices.js";
import { createMfaResource } from "./resources/mfa.js";
import { createPasskeysResource } from "./resources/passkeys.js";

export type ApiKey = components["schemas"]["ApiKeyDto"];
export type CreateApiKeyDto = components["schemas"]["CreateApiKeyDto"];
export type CartListItem = components["schemas"]["CartListItem"];
export type CartDetail = components["schemas"]["CartDetail"];
export type PaginatedCarts = components["schemas"]["PaginatedCarts"];
export type Product = components["schemas"]["Product"];
export type PaginatedProducts = components["schemas"]["PaginatedProducts"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductVariant = components["schemas"]["ProductVariant"];
export type ProductOption = components["schemas"]["ProductOption"];
export type ProductImage = components["schemas"]["ProductImage"];
export type GetImageUploadUrlDto =
  components["schemas"]["GetImageUploadUrlDto"];
export type CreateVariantsDto = components["schemas"]["CreateVariantsDto"];
export type Brand = components["schemas"]["Brand"];
export type PaginatedBrands = components["schemas"]["PaginatedBrands"];
export type Category = components["schemas"]["Category"];
export type CategoryListItem = components["schemas"]["CategoryListItem"];
export type PaginatedCategories = components["schemas"]["PaginatedCategories"];
export type Location = components["schemas"]["Location"];
export type PaginatedLocations = components["schemas"]["PaginatedLocations"];
export type InventoryRecord = components["schemas"]["InventoryRecord"];
export type PaginatedInventory = components["schemas"]["PaginatedInventory"];
export type InventoryMovementRecord =
  components["schemas"]["InventoryMovementRecord"];
export type PaginatedInventoryMovements =
  components["schemas"]["PaginatedInventoryMovements"];
export type StripeConnectStatus = components["schemas"]["StripeConnectStatus"];
export type OrderListItem = components["schemas"]["OrderListItem"];
export type OrderDetail = components["schemas"]["OrderDetail"];
export type OrderDetailItem = components["schemas"]["OrderDetailItem"];
export type OrderShippingInfo = components["schemas"]["OrderShippingInfo"];
export type OrderPayment = components["schemas"]["OrderPayment"];
export type OrderEvent = components["schemas"]["OrderEvent"];
export type OrderStatusChange = components["schemas"]["OrderStatusChange"];
export type UpdateOrderStatusDto =
  components["schemas"]["UpdateOrderStatusDto"];
export type OrderRefund = components["schemas"]["OrderRefund"];
export type RefundOrderDto = components["schemas"]["RefundOrderDto"];
export type RefundLineDto = components["schemas"]["RefundLineDto"];
export type OrderCancellation = components["schemas"]["OrderCancellation"];
export type CancelOrderDto = components["schemas"]["CancelOrderDto"];
export type OrderItemAllocation = components["schemas"]["OrderItemAllocation"];
export type Fulfillment = components["schemas"]["Fulfillment"];
export type FulfillmentItem = components["schemas"]["FulfillmentItem"];
export type ShippingRate = components["schemas"]["ShippingRate"];
export type PaginatedOrders = components["schemas"]["PaginatedOrders"];
export type FailedOrder = components["schemas"]["FailedOrder"];
export type FailedOrdersList = components["schemas"]["FailedOrdersList"];
export type Account = components["schemas"]["Account"];
export type User = components["schemas"]["User"];
export type PaginatedUsers = components["schemas"]["PaginatedUsers"];
export type CreateUserDto = components["schemas"]["CreateUserDto"];
export type Customer = components["schemas"]["Customer"];
export type CustomerDetail = components["schemas"]["CustomerDetail"];
export type CustomerOrderSummary =
  components["schemas"]["CustomerOrderSummary"];
export type PaginatedCustomers = components["schemas"]["PaginatedCustomers"];
export type PaginatedCustomerOrders =
  components["schemas"]["PaginatedCustomerOrders"];
export type AcceptInviteDto = components["schemas"]["AcceptInviteDto"];
export type AuthMe = components["schemas"]["AuthMe"];
export type UserProfile = components["schemas"]["UserProfile"];
export type UpdateUserProfileDto =
  components["schemas"]["UpdateUserProfileDto"];
export type ChangePasswordDto = components["schemas"]["ChangePasswordDto"];
export type AccessTokenDto = components["schemas"]["AccessTokenDto"];
export type DashboardSummary = components["schemas"]["DashboardSummary"];
export type OnboardingStatus = components["schemas"]["OnboardingStatus"];
export type Permission = components["schemas"]["Permission"];
export type Role = components["schemas"]["Role"];
export type RoleDetail = components["schemas"]["RoleDetail"];
export type CreateRoleDto = components["schemas"]["CreateRoleDto"];
export type UpdateRoleDto = components["schemas"]["UpdateRoleDto"];
export type PosDevice = components["schemas"]["PosDevice"];
export type PosDevicePairing = components["schemas"]["PosDevicePairing"];
export type CreatePosDeviceDto = components["schemas"]["CreatePosDeviceDto"];
export type UpdatePosDeviceDto = components["schemas"]["UpdatePosDeviceDto"];
export type MfaEnrollResponse =
  components["schemas"]["MfaEnrollResponseDto"];
export type MfaRecoveryCodes = components["schemas"]["MfaRecoveryCodesDto"];
export type MfaConfirmDto = components["schemas"]["MfaConfirmDto"];
export type MfaConfirmResponse =
  components["schemas"]["MfaConfirmResponseDto"];
export type MfaDisableDto = components["schemas"]["MfaDisableDto"];
export type MfaRegenerateRecoveryCodesDto =
  components["schemas"]["MfaRegenerateRecoveryCodesDto"];
export type MfaVerifyDto = components["schemas"]["MfaVerifyDto"];
export type MfaChallenge = components["schemas"]["MfaChallengeDto"];
export type Passkey = components["schemas"]["PasskeyDto"];
export type PasskeyRegisterVerifyDto =
  components["schemas"]["PasskeyRegisterVerifyDto"];
export type PasskeyRegistered =
  components["schemas"]["PasskeyRegisteredDto"];
export type PasskeyRenameDto = components["schemas"]["PasskeyRenameDto"];
export type PasskeyRemoveDto = components["schemas"]["PasskeyRemoveDto"];
export type PasskeyChallengeOptionsDto =
  components["schemas"]["PasskeyChallengeOptionsDto"];
export type PasskeyChallengeVerifyDto =
  components["schemas"]["PasskeyChallengeVerifyDto"];
export type PasskeySignInVerifyDto =
  components["schemas"]["PasskeySignInVerifyDto"];

export class AdminClient {
  accessToken: string | undefined;
  client: Client<paths>;

  products: ReturnType<typeof createProductsResource>;
  brands: ReturnType<typeof createBrandsResource>;
  categories: ReturnType<typeof createCategoriesResource>;
  locations: ReturnType<typeof createLocationsResource>;
  inventory: ReturnType<typeof createInventoryResource>;
  apiKeys: ReturnType<typeof createApiKeysResource>;
  carts: ReturnType<typeof createCartsResource>;
  stripeConnect: ReturnType<typeof createStripeConnectResource>;
  orders: ReturnType<typeof createOrdersResource>;
  failedOrders: ReturnType<typeof createFailedOrdersResource>;
  fulfillments: ReturnType<typeof createFulfillmentsResource>;
  account: ReturnType<typeof createAccountResource>;
  users: ReturnType<typeof createUsersResource>;
  customers: ReturnType<typeof createCustomersResource>;
  dashboard: ReturnType<typeof createDashboardResource>;
  onboarding: ReturnType<typeof createOnboardingResource>;
  roles: ReturnType<typeof createRolesResource>;
  permissions: ReturnType<typeof createPermissionsResource>;
  posDevices: ReturnType<typeof createPosDevicesResource>;
  mfa: ReturnType<typeof createMfaResource>;
  passkeys: ReturnType<typeof createPasskeysResource>;

  // every request needs the bearer token and the cross-origin cookie
  // (for the refresh_token) — centralized here instead of at each call site.
  // Request.headers is mutable in place, but credentials isn't, so that part
  // has to go through a rebuilt Request.
  private authMiddleware: Middleware = {
    onRequest: ({ request }) => {
      request.headers.set("Authorization", `Bearer ${this.accessToken}`);
      return new Request(request, { credentials: "include" });
    },
  };

  constructor(baseUrl: string) {
    this.client = createClient({ baseUrl });
    this.client.use(this.authMiddleware);

    const doRequest: DoFn = (request) => this.do(request);

    this.products = createProductsResource(this.client, doRequest);
    this.brands = createBrandsResource(this.client, doRequest);
    this.categories = createCategoriesResource(this.client, doRequest);
    this.locations = createLocationsResource(this.client, doRequest);
    this.inventory = createInventoryResource(this.client, doRequest);
    this.apiKeys = createApiKeysResource(this.client, doRequest);
    this.carts = createCartsResource(this.client, doRequest);
    this.stripeConnect = createStripeConnectResource(this.client, doRequest);
    this.orders = createOrdersResource(this.client, doRequest);
    this.failedOrders = createFailedOrdersResource(this.client, doRequest);
    this.fulfillments = createFulfillmentsResource(this.client, doRequest);
    this.account = createAccountResource(this.client, doRequest);
    this.users = createUsersResource(this.client, doRequest);
    this.customers = createCustomersResource(this.client, doRequest);
    this.dashboard = createDashboardResource(this.client, doRequest);
    this.onboarding = createOnboardingResource(this.client, doRequest);
    this.roles = createRolesResource(this.client, doRequest);
    this.permissions = createPermissionsResource(this.client, doRequest);
    this.posDevices = createPosDevicesResource(this.client, doRequest);
    this.mfa = createMfaResource(
      this.client,
      doRequest,
      (token) => (this.accessToken = token),
    );
    this.passkeys = createPasskeysResource(
      this.client,
      doRequest,
      (token) => (this.accessToken = token),
    );
  }

  // returns either an access token (sets it on the client, same as before)
  // or an MFA challenge (OS-316) — the caller narrows on `mfaRequired` to
  // tell them apart and, in the challenge case, exchanges it via
  // verifyMfaChallenge() (OS-475). Throws ApiError with the server's
  // message on a non-2xx (wrong password) — previously this silently
  // resolved `undefined` instead (openapi-fetch doesn't throw by default),
  // so a failed sign-in fell through to the success path in the UI.
  async signIn(credentials: components["schemas"]["SignInDto"]) {
    const result = unwrap(
      await this.client.POST("/auth/signin", { body: credentials }),
    );
    if ("access_token" in result) {
      this.accessToken = result.access_token;
    }
    return result;
  }

  // exchanges a signin()-issued challenge (TOTP or recovery code) for real
  // tokens — public because the caller isn't holding a session yet, same
  // shape as signIn()
  async verifyMfaChallenge(params: components["schemas"]["MfaVerifyDto"]) {
    const result = unwrap(
      await this.client.POST("/auth/mfa/verify", { body: params }),
    );
    this.accessToken = result.access_token;
    return this.accessToken;
  }

  // throws ApiError on failure — see signIn()'s comment, same pre-existing
  // silent-resolve gap fixed here
  async signUp(signup: components["schemas"]["SignUpDto"]) {
    const result = unwrap(
      await this.client.POST("/auth/signup", { body: signup }),
    );
    this.accessToken = result.access_token;
    return this.accessToken;
  }

  // throws ApiError on failure — see signIn()'s comment, same pre-existing
  // silent-resolve gap fixed here
  async acceptInvite(params: components["schemas"]["AcceptInviteDto"]) {
    const result = unwrap(
      await this.client.POST("/auth/accept-invite", { body: params }),
    );
    this.accessToken = result.access_token;
    return this.accessToken;
  }

  // public; resolves the same whether or not the email has an account, so
  // callers must not branch on it (no account enumeration)
  async forgotPassword(params: components["schemas"]["ForgotPasswordDto"]) {
    unwrap(
      await this.client.POST("/auth/forgot-password", { body: params }),
    );
  }

  // public — the user can't sign in by definition. Never logs in: the API
  // revokes every session for the user, and MFA still applies on next
  // sign-in. 401 = bad/expired link, 400 = password rejected by policy.
  async resetPassword(params: components["schemas"]["ResetPasswordDto"]) {
    unwrap(
      await this.client.POST("/auth/reset-password", { body: params }),
    );
    this.accessToken = undefined;
  }

  // requires a session — the emailed token only proves inbox control, it
  // never logs anyone in. Returns the caller's re-minted access token
  // (emailVerified: true). Retries a 401 once like do(), but deliberately
  // not through do(): its generic 403 rewrite would hide the API's
  // "belongs to a different account" message. Bad/expired tokens are 400.
  async verifyEmail(params: components["schemas"]["VerifyEmailDto"]) {
    const request = () =>
      this.client.POST("/auth/verify-email", { body: params });
    let response = await request();
    if (response.response.status === 401) {
      await this.refreshAccessToken();
      response = await request();
    }
    this.accessToken = unwrap(response).access_token;
    return this.accessToken;
  }

  async resendVerification() {
    unwrap(
      await this.do(() => this.client.POST("/auth/verify-email/resend")),
    );
  }

  async refreshAccessToken() {
    // POST, not GET — this now mutates server-side refresh-token state
    // (rotation), so it shouldn't be reachable via prefetch/link-scanning
    const { data } = await this.client.POST("/auth/token/refresh");
    this.accessToken = data?.access_token;
    return this.accessToken;
  }

  // current user identity + effective permission keys — merchant-web's
  // permission context. Retries once on 401 via do().
  async me() {
    const { data } = await this.do(() => this.client.GET("/auth/me"));
    return data;
  }

  // the caller's own editable attributes (name + phone). Deliberately a
  // separate call from me(): that response is cached with a staleTime and
  // cleared on every auth mutation, which is the wrong lifecycle for the
  // values backing a form the user edits. Unwrapped so a failed read throws
  // rather than resolving `undefined` into a blank form.
  async profile() {
    return unwrap(await this.do(() => this.client.GET("/auth/me/profile")));
  }

  // writes the caller's own name/phone. There is no id: the endpoint can only
  // ever address the signed-in user, which is why it needs no permission.
  // Throws ApiError with the server's message on a non-2xx.
  async updateProfile(params: components["schemas"]["UpdateUserProfileDto"]) {
    return unwrap(
      await this.do(() =>
        this.client.PATCH("/auth/me/profile", { body: params }),
      ),
    );
  }

  // the signed-in counterpart to resetPassword(): re-authenticates with the
  // current password rather than an emailed link. The API revokes every other
  // live session and rotates this browser's refresh cookie in place, so the
  // caller stays signed in here; the re-minted access token it hands back is
  // adopted because it carries claims recomputed from the database.
  // 401 = current password wrong, 400 = new password rejected by policy.
  async changePassword(params: components["schemas"]["ChangePasswordDto"]) {
    const result = unwrap(
      await this.do(() =>
        this.client.POST("/auth/me/change-password", { body: params }),
      ),
    );
    this.accessToken = result.access_token;
    return result;
  }

  // ends every OTHER session this user holds, leaving this browser signed
  // in. Unlike changePassword() there's no replacement token to adopt and no
  // password to send: the API spares the family named by this browser's
  // refresh cookie and doesn't rotate it, so nothing here changes.
  async revokeOtherSessions() {
    unwrap(
      await this.do(() => this.client.POST("/auth/me/sessions/revoke-all")),
    );
  }

  // clears the httpOnly refresh_token cookie server-side — the client can't
  // delete it itself — then drops the in-memory access token
  async logout() {
    await this.client.POST("/auth/logout");
    this.accessToken = undefined;
  }

  // request is a thunk so the retry rebuilds headers off the refreshed accessToken, not a stale one
  private async do<T>(
    request: () => Promise<{ data?: T; error?: unknown; response: Response }>,
  ) {
    let result = await request();
    if (result.response.status === 401) {
      await this.refreshAccessToken();
      result = await request();
    }
    // A 403 is never a "normal" empty result, so surface it as an ApiError
    // for reads too — they'd otherwise return undefined data silently.
    //
    // Two kinds reach here now. PermissionsGuard denies a missing permission
    // with a plain message, and that gets the friendly generic string, since
    // the server's wording isn't written for merchants. MfaFactorGuard
    // (OS-492) denies an action that needs a passkey or authenticator and
    // attaches a `code`, which the UI has to branch on to offer setting one
    // up — so when a code is present, the server's own message and code are
    // passed through intact.
    //
    // Before this, every 403 was flattened to the generic string, so the two
    // were indistinguishable and the factor-required prompt would have shown
    // "You don't have permission to do this." instead.
    if (result.response.status === 403) {
      const { message, code } = readErrorBody(result.error);
      throw new ApiError(
        code && message ? message : "You don't have permission to do this.",
        403,
        code,
      );
    }
    return result;
  }
}
