import createClient, { type Client, type Middleware } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import { unwrap, unwrapOrUndefinedOn, type DoFn } from "./http.js";
export { ApiError } from "./http.js";
import { createProductsResource } from "./resources/products.js";
import { createCategoriesResource } from "./resources/categories.js";
import { createBrandsResource } from "./resources/brands.js";
import { createCartResource } from "./resources/cart.js";
import { createCheckoutResource } from "./resources/checkout.js";
import { createCustomerResource } from "./resources/customer.js";

export type ProductListItem = components["schemas"]["ProductListItem"];
export type PaginatedProducts = components["schemas"]["PaginatedProducts"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductDetailOption = components["schemas"]["ProductDetailOption"];
export type ProductDetailVariant =
  components["schemas"]["ProductDetailVariant"];
export type Category = components["schemas"]["Category"];
export type PaginatedCategories = components["schemas"]["PaginatedCategories"];
export type CategoryDetail = components["schemas"]["CategoryDetail"];
export type Brand = components["schemas"]["Brand"];
export type PaginatedBrands = components["schemas"]["PaginatedBrands"];
export type BrandDetail = components["schemas"]["BrandDetail"];
export type Cart = components["schemas"]["Cart"];
export type CartItem = components["schemas"]["CartItem"];
export type CheckoutSession = components["schemas"]["CheckoutSession"];
export type CheckoutConfig = components["schemas"]["CheckoutConfig"];
export type CheckoutSessionStatus =
  components["schemas"]["CheckoutSessionStatus"];
export type Customer = components["schemas"]["Customer"];
export type CustomerSignUpDto = components["schemas"]["CustomerSignUpDto"];
export type CustomerSignInDto = components["schemas"]["CustomerSignInDto"];
export type UpdateCustomerDto = components["schemas"]["UpdateCustomerDto"];

const APP_KEY_HEADER = "x-app-key";

export interface StorefrontClientTokens {
  accessToken: string | undefined;
  refreshToken: string | undefined;
}

export interface StorefrontClientOptions {
  // fired after signUp()/signIn()/refreshAccessToken()/logout() whenever
  // either token changes, with the current values — the recommended way to
  // keep a persisted copy (e.g. localStorage) in sync. Refresh tokens are
  // single-use and rotate on every refreshAccessToken() call (OS-457): the
  // value here after a refresh is the only one still valid going forward,
  // and a logout call passes both as undefined so persisted storage can be
  // cleared too.
  onTokensChanged?: (tokens: StorefrontClientTokens) => void;
}

export class StorefrontClient {
  appKey: string;
  // set automatically the first time cart.addItem() creates a cart — or
  // pass one in up front (e.g. restored from localStorage) to resume a cart
  cartToken: string | undefined;
  // set by signUp()/signIn() and by a successful refreshAccessToken() — see
  // the onTokensChanged constructor option to persist this across reloads
  accessToken: string | undefined;
  // set by signUp()/signIn()/refreshAccessToken() — pass one in up front
  // (e.g. restored from localStorage) to re-derive an accessToken via
  // refreshAccessToken() on page load. Single-use: rotates on every
  // refreshAccessToken() call, so a stale copy stops working the moment a
  // newer one is issued — use onTokensChanged, not this field directly, to
  // keep a persisted copy current. Tokens live in the request/response
  // body, not a cookie: a storefront can be hosted on any merchant-owned
  // domain, and a cookie set by storefront-api never rides along on a
  // genuinely cross-site fetch.
  refreshToken: string | undefined;
  client: Client<paths>;
  private onTokensChanged?: StorefrontClientOptions["onTokensChanged"];
  private refreshInFlight: Promise<string | undefined> | undefined;
  // bumped whenever the session is replaced (signUp/signIn/logout) — a
  // refresh started under an older session discards its result on landing
  private sessionGeneration = 0;

  products: ReturnType<typeof createProductsResource>;
  categories: ReturnType<typeof createCategoriesResource>;
  brands: ReturnType<typeof createBrandsResource>;
  cart: ReturnType<typeof createCartResource>;
  checkout: ReturnType<typeof createCheckoutResource>;
  customer: ReturnType<typeof createCustomerResource>;

  // every authenticated request needs the bearer token — centralized here
  // instead of at each call site, same pattern as merchant-sdk's AdminClient
  private authMiddleware: Middleware = {
    onRequest: ({ request }) => {
      request.headers.set("Authorization", `Bearer ${this.accessToken}`);
      return request;
    },
  };

  constructor(
    baseUrl: string,
    appKey: string,
    cartToken?: string,
    refreshToken?: string,
    options?: StorefrontClientOptions,
  ) {
    this.appKey = appKey;
    this.cartToken = cartToken;
    this.refreshToken = refreshToken;
    this.onTokensChanged = options?.onTokensChanged;
    this.client = createClient({ baseUrl });
    // the app key identifies the tenant on every request — read off `this`
    // rather than captured at construction, so reassigning `appKey` later
    // (e.g. switching storefronts) takes effect immediately
    this.client.use({
      onRequest: ({ request }) => {
        request.headers.set(APP_KEY_HEADER, this.appKey);
        return request;
      },
    });
    this.client.use(this.authMiddleware);

    const doRequest: DoFn = (request) => this.do(request);

    this.products = createProductsResource(this.client);
    this.categories = createCategoriesResource(this.client);
    this.brands = createBrandsResource(this.client);
    this.cart = createCartResource(
      this.client,
      () => this.cartToken,
      (token) => {
        this.cartToken = token;
      },
    );
    this.checkout = createCheckoutResource(this.client, () => this.cartToken);
    this.customer = createCustomerResource(this.client, doRequest);
  }

  async signUp(signup: CustomerSignUpDto) {
    const result = await this.client.POST("/v1/auth/signup", { body: signup });
    const tokens = unwrap(result);
    this.supersedeSession();
    this.accessToken = tokens.access_token;
    this.refreshToken = tokens.refresh_token;
    this.emitTokensChanged();
    return this.accessToken;
  }

  // sends the current cart token (if any) so the backend can claim the
  // guest cart into the newly-signed-in customer's account
  async signIn(credentials: CustomerSignInDto) {
    const result = await this.client.POST("/v1/auth/signin", {
      body: credentials,
      headers: this.cartToken ? { "x-cart-token": this.cartToken } : {},
    });
    const tokens = unwrap(result);
    this.supersedeSession();
    this.accessToken = tokens.access_token;
    this.refreshToken = tokens.refresh_token;
    this.emitTokensChanged();
    return this.accessToken;
  }

  // no refreshToken (never signed in, or already logged out) — nothing to
  // refresh with, the same "not signed in" outcome as an expected 401.
  // Otherwise, a 401 means the refresh token itself is invalid/expired —
  // anything else (a real 500/network failure) should surface, not silently
  // leave accessToken unset. The server rotates on every call (OS-457) —
  // the response's refresh_token replaces this.refreshToken, and the old
  // value must not be reused, so onTokensChanged is the only reliable way
  // to keep a persisted copy in sync.
  //
  // Single-flight (OS-690): concurrent callers share the one in-flight
  // refresh instead of each redeeming the same single-use token — the
  // second redemption would look like reuse and revoke the whole session.
  // Cleared once it settles either way, so a failed refresh isn't handed
  // out again to the next caller.
  refreshAccessToken(): Promise<string | undefined> {
    if (!this.refreshInFlight) {
      const inFlight = this.redeemRefreshToken().finally(() => {
        // a superseded refresh mustn't clear a newer session's one
        if (this.refreshInFlight === inFlight) this.refreshInFlight = undefined;
      });
      this.refreshInFlight = inFlight;
    }
    return this.refreshInFlight;
  }

  private async redeemRefreshToken() {
    if (!this.refreshToken) {
      this.accessToken = undefined;
      this.emitTokensChanged();
      return undefined;
    }
    const generation = this.sessionGeneration;
    const result = await this.client.POST("/v1/auth/token/refresh", {
      body: { refresh_token: this.refreshToken },
    });
    // logged out or signed in as someone else while this was in flight —
    // applying it would resurrect (or overwrite) the session. Hand callers
    // whatever the current session holds instead.
    if (generation !== this.sessionGeneration) return this.accessToken;
    const tokens = unwrapOrUndefinedOn(result, 401);
    this.accessToken = tokens?.access_token;
    this.refreshToken = tokens?.refresh_token;
    if (this.accessToken === undefined) this.refreshToken = undefined;
    this.emitTokensChanged();
    return this.accessToken;
  }

  // Clears local state synchronously (so it's already gone by the time this
  // returns control, even if the caller doesn't await it) before making a
  // best-effort call to actually revoke the session server-side (OS-458) —
  // a failed network call shouldn't trap the caller in a "can't log out"
  // state, since the local tokens are dropped either way.
  async logout(): Promise<void> {
    const refreshToken = this.refreshToken;
    this.supersedeSession();
    this.accessToken = undefined;
    this.refreshToken = undefined;
    this.emitTokensChanged();

    if (refreshToken) {
      try {
        await this.client.POST("/v1/auth/logout", {
          body: { refresh_token: refreshToken },
        });
      } catch {
        // best-effort — local state is already cleared above regardless
      }
    }
  }

  // a new session (or none) replaces the current one — any refresh still in
  // flight belongs to the old session, so later callers start fresh rather
  // than joining it
  private supersedeSession() {
    this.sessionGeneration++;
    this.refreshInFlight = undefined;
  }

  private emitTokensChanged() {
    this.onTokensChanged?.({
      accessToken: this.accessToken,
      refreshToken: this.refreshToken,
    });
  }

  // request is a thunk so the retry rebuilds headers off the refreshed accessToken, not a stale one
  private async do<T>(
    request: () => Promise<{ data?: T; error?: unknown; response: Response }>,
  ) {
    const accessTokenSent = this.accessToken;
    const result = await request();
    if (result.response.status === 401) {
      // if another call already refreshed while this one was in flight, its
      // 401 is stale — retry with the new token rather than rotating again
      if (this.accessToken === accessTokenSent) {
        await this.refreshAccessToken();
      }
      return await request();
    }
    return result;
  }
}
