import createClient, { type Client, type Middleware } from "openapi-fetch";
import type { paths, components } from "./types.gen.js"; // generated by openapi-typescript
import { unwrap, unwrapOrUndefinedOn, type DoFn } from "./http.js";
export { ApiError } from "./http.js";
import { createProductsResource } from "./resources/products.js";
import { createCartResource } from "./resources/cart.js";
import { createCheckoutResource } from "./resources/checkout.js";
import { createCustomerResource } from "./resources/customer.js";

export type ProductListItem = components["schemas"]["ProductListItem"];
export type PaginatedProducts = components["schemas"]["PaginatedProducts"];
export type ProductDetail = components["schemas"]["ProductDetail"];
export type ProductDetailOption = components["schemas"]["ProductDetailOption"];
export type ProductDetailVariant = components["schemas"]["ProductDetailVariant"];
export type Cart = components["schemas"]["Cart"];
export type CartItem = components["schemas"]["CartItem"];
export type CheckoutSession = components["schemas"]["CheckoutSession"];
export type CheckoutConfig = components["schemas"]["CheckoutConfig"];
export type CheckoutSessionStatus = components["schemas"]["CheckoutSessionStatus"];
export type Customer = components["schemas"]["Customer"];
export type CustomerSignUpDto = components["schemas"]["CustomerSignUpDto"];
export type CustomerSignInDto = components["schemas"]["CustomerSignInDto"];
export type UpdateCustomerDto = components["schemas"]["UpdateCustomerDto"];

const APP_KEY_HEADER = "x-app-key";

export class StorefrontClient {
  appKey: string;
  // set automatically the first time cart.addItem() creates a cart — or
  // pass one in up front (e.g. restored from localStorage) to resume a cart
  cartToken: string | undefined;
  // set by signUp()/signIn() and by a successful refreshAccessToken() — not
  // persisted by the SDK itself; a consuming app that wants a session to
  // survive a page reload restores it from wherever it stored refreshToken
  accessToken: string | undefined;
  // set by signUp()/signIn() — pass one in up front (e.g. restored from
  // localStorage) to re-derive an accessToken via refreshAccessToken() on
  // page load. Tokens live in the request/response body, not a cookie: a
  // storefront can be hosted on any merchant-owned domain, and a cookie set
  // by storefront-api never rides along on a genuinely cross-site fetch.
  refreshToken: string | undefined;
  client: Client<paths>;

  products: ReturnType<typeof createProductsResource>;
  cart: ReturnType<typeof createCartResource>;
  checkout: ReturnType<typeof createCheckoutResource>;
  customer: ReturnType<typeof createCustomerResource>;

  // every authenticated request needs the bearer token — centralized here
  // instead of at each call site, same pattern as merchant-sdk's AdminClient
  private authMiddleware: Middleware = {
    onRequest: ({ request }) => {
      request.headers.set("Authorization", `Bearer ${this.accessToken}`);
      return request;
    },
  };

  constructor(
    baseUrl: string,
    appKey: string,
    cartToken?: string,
    refreshToken?: string,
  ) {
    this.appKey = appKey;
    this.cartToken = cartToken;
    this.refreshToken = refreshToken;
    this.client = createClient({ baseUrl });
    // the app key identifies the tenant on every request — read off `this`
    // rather than captured at construction, so reassigning `appKey` later
    // (e.g. switching storefronts) takes effect immediately
    this.client.use({
      onRequest: ({ request }) => {
        request.headers.set(APP_KEY_HEADER, this.appKey);
        return request;
      },
    });
    this.client.use(this.authMiddleware);

    const doRequest: DoFn = (request) => this.do(request);

    this.products = createProductsResource(this.client);
    this.cart = createCartResource(
      this.client,
      () => this.cartToken,
      (token) => {
        this.cartToken = token;
      },
    );
    this.checkout = createCheckoutResource(this.client, () => this.cartToken);
    this.customer = createCustomerResource(this.client, doRequest);
  }

  async signUp(signup: CustomerSignUpDto) {
    const result = await this.client.POST("/auth/signup", { body: signup });
    const tokens = unwrap(result);
    this.accessToken = tokens.access_token;
    this.refreshToken = tokens.refresh_token;
    return this.accessToken;
  }

  // sends the current cart token (if any) so the backend can claim the
  // guest cart into the newly-signed-in customer's account
  async signIn(credentials: CustomerSignInDto) {
    const result = await this.client.POST("/auth/signin", {
      body: credentials,
      headers: this.cartToken ? { "x-cart-token": this.cartToken } : {},
    });
    const tokens = unwrap(result);
    this.accessToken = tokens.access_token;
    this.refreshToken = tokens.refresh_token;
    return this.accessToken;
  }

  // no refreshToken (never signed in, or already logged out) — nothing to
  // refresh with, the same "not signed in" outcome as an expected 401.
  // Otherwise, a 401 means the refresh token itself is invalid/expired —
  // anything else (a real 500/network failure) should surface, not silently
  // leave accessToken unset
  async refreshAccessToken() {
    if (!this.refreshToken) {
      this.accessToken = undefined;
      return undefined;
    }
    const result = await this.client.POST("/auth/token/refresh", {
      body: { refresh_token: this.refreshToken },
    });
    this.accessToken = unwrapOrUndefinedOn(result, 401)?.access_token;
    if (this.accessToken === undefined) this.refreshToken = undefined;
    return this.accessToken;
  }

  // nothing server-side to clear (no cookie, and no revocation store for
  // these short-lived JWTs) — just drop the tokens this client is holding
  logout() {
    this.accessToken = undefined;
    this.refreshToken = undefined;
  }

  // request is a thunk so the retry rebuilds headers off the refreshed accessToken, not a stale one
  private async do<T>(
    request: () => Promise<{ data?: T; error?: unknown; response: Response }>,
  ) {
    const result = await request();
    if (result.response.status === 401) {
      await this.refreshAccessToken();
      return await request();
    }
    return result;
  }
}
