/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BrandsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CartController_getCart"];
        put?: never;
        post?: never;
        delete: operations["CartController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/items/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CartController_removeItem"];
        options?: never;
        head?: never;
        patch: operations["CartController_updateItem"];
        trace?: never;
    };
    "/v1/checkout/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CheckoutController_getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkout/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CheckoutController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkout/shipping-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CheckoutController_getShippingOptions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkout/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CheckoutController_getSessionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomerController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["CustomerController_update"];
        trace?: never;
    };
    "/v1/customer/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomerOrdersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomerOrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProductListBrand: {
            id: number;
            name: string;
        };
        ProductListCategory: {
            id: number;
            name: string;
        };
        ProductListItem: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["ProductListBrand"] | null;
            categories: components["schemas"]["ProductListCategory"][];
            minPriceCents: number | null;
            maxPriceCents: number | null;
            thumbnailUrl: string | null;
        };
        PaginatedProducts: {
            items: components["schemas"]["ProductListItem"][];
            total: number;
            limit: number;
            offset: number;
        };
        ProductDetailBrand: {
            id: number;
            name: string;
        };
        ProductDetailCategory: {
            id: number;
            name: string;
        };
        ProductDetailOptionValue: {
            id: number;
            value: string;
        };
        ProductDetailOption: {
            id: number;
            name: string;
            values: components["schemas"]["ProductDetailOptionValue"][];
        };
        VariantOptionValue: {
            optionName: string;
            value: string;
        };
        ProductImage: {
            id: number;
            url: string;
            position: number;
        };
        ProductDetailVariant: {
            id: number;
            sku: string | null;
            priceCents: number;
            stock: number;
            optionValues: components["schemas"]["VariantOptionValue"][];
            images: components["schemas"]["ProductImage"][];
        };
        ProductDetail: {
            id: number;
            name: string;
            description: string | null;
            brand: components["schemas"]["ProductDetailBrand"] | null;
            categories: components["schemas"]["ProductDetailCategory"][];
            options: components["schemas"]["ProductDetailOption"][];
            variants: components["schemas"]["ProductDetailVariant"][];
            images: components["schemas"]["ProductImage"][];
        };
        Category: {
            id: number;
            name: string;
            productCount: number;
        };
        PaginatedCategories: {
            items: components["schemas"]["Category"][];
            total: number;
            limit: number;
            offset: number;
        };
        CategoryDetail: {
            id: number;
            name: string;
            products: components["schemas"]["PaginatedProducts"];
        };
        Brand: {
            id: number;
            name: string;
            productCount: number;
        };
        PaginatedBrands: {
            items: components["schemas"]["Brand"][];
            total: number;
            limit: number;
            offset: number;
        };
        BrandDetail: {
            id: number;
            name: string;
            products: components["schemas"]["PaginatedProducts"];
        };
        AddCartItemDto: {
            variantId: number;
            /** @default 1 */
            quantity: number;
        };
        CartItemOptionValue: {
            optionName: string;
            value: string;
        };
        CartItem: {
            variantId: number;
            productId: number;
            productName: string;
            sku: string | null;
            priceCents: number;
            quantity: number;
            stock: number;
            optionValues: components["schemas"]["CartItemOptionValue"][];
        };
        Cart: {
            token: string;
            items: components["schemas"]["CartItem"][];
            subtotalCents: number;
            itemCount: number;
        };
        UpdateCartItemDto: {
            quantity: number;
        };
        CheckoutConfig: {
            ready: boolean;
            stripeAccountId: string | null;
        };
        CreateCheckoutSessionDto: {
            returnUrl: string;
        };
        CheckoutSession: {
            clientSecret: string;
        };
        ShippingAddressDto: {
            country: string;
            line1?: string;
            line2?: string;
            city?: string;
            postal_code?: string;
            state?: string;
        };
        ShippingDetailsDto: {
            name: string;
            address: components["schemas"]["ShippingAddressDto"];
        };
        GetShippingOptionsDto: {
            checkoutSessionId: string;
            shippingDetails: components["schemas"]["ShippingDetailsDto"];
        };
        ShippingOptionsResult: {
            ok: boolean;
            errorMessage?: string;
        };
        CheckoutSessionStatus: {
            status: string;
            paymentStatus: string;
            customerEmail: string | null;
        };
        Customer: {
            id: number;
            accountId: number;
            firstName: string;
            lastName: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateCustomerDto: {
            firstName?: string;
            lastName?: string;
            email?: string;
        };
        CustomerOrderSummary: {
            id: number;
            /** @enum {string} */
            status: "pending" | "paid" | "partially_refunded" | "refunded" | "canceled" | "payment_failed";
            /** @enum {string} */
            fulfillmentStatus: "unfulfilled" | "partially_fulfilled" | "fulfilled";
            itemCount: number;
            amountTotalCents: number;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedCustomerOrders: {
            items: components["schemas"]["CustomerOrderSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        CustomerOrderShipping: {
            line1: string;
            line2: string | null;
            city: string;
            state: string | null;
            postalCode: string;
            country: string;
        };
        CustomerOrderPayment: {
            /** @enum {string} */
            method: "stripe" | "cash" | "card";
            amountCents: number;
            /** Format: date-time */
            createdAt: string;
        };
        CustomerOrderItem: {
            id: number;
            variantId: number | null;
            productName: string;
            sku: string | null;
            optionsLabel: string | null;
            priceCents: number;
            quantity: number;
            fulfilledQuantity: number;
            refundedQuantity: number;
        };
        CustomerFulfillmentItem: {
            orderItemId: number;
            quantity: number;
        };
        CustomerOrderFulfillment: {
            id: number;
            shippingCarrier: string | null;
            shippingServiceLevel: string | null;
            trackingNumber: string | null;
            trackingUrl: string | null;
            /** Format: date-time */
            createdAt: string;
            items: components["schemas"]["CustomerFulfillmentItem"][];
        };
        CustomerOrderDetail: {
            id: number;
            /** @enum {string} */
            status: "pending" | "paid" | "partially_refunded" | "refunded" | "canceled" | "payment_failed";
            /** @enum {string} */
            fulfillmentStatus: "unfulfilled" | "partially_fulfilled" | "fulfilled";
            customerName: string | null;
            customerEmail: string | null;
            shipping: components["schemas"]["CustomerOrderShipping"] | null;
            subtotalCents: number;
            shippingCents: number;
            taxCents: number;
            amountTotalCents: number;
            payments: components["schemas"]["CustomerOrderPayment"][];
            items: components["schemas"]["CustomerOrderItem"][];
            fulfillments: components["schemas"]["CustomerOrderFulfillment"][];
            /** Format: date-time */
            createdAt: string;
        };
        CustomerSignUpDto: {
            firstName: string;
            lastName: string;
            email: string;
            password: string;
        };
        TokenPairDto: {
            access_token: string;
            refresh_token: string;
        };
        CustomerSignInDto: {
            email: string;
            password: string;
        };
        RefreshTokenDto: {
            refresh_token: string;
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                type: "invalid_request_error" | "authentication_error" | "permission_error" | "rate_limit_error" | "api_error";
                /** @enum {string} */
                code: "bad_request" | "unauthenticated" | "forbidden" | "not_found" | "method_not_allowed" | "not_acceptable" | "request_timeout" | "conflict" | "gone" | "precondition_failed" | "content_too_large" | "unsupported_media_type" | "misdirected_request" | "unprocessable_content" | "rate_limited" | "internal_error" | "not_implemented" | "bad_gateway" | "service_unavailable" | "gateway_timeout" | "http_version_not_supported" | "validation_failed" | "invalid_access_token" | "invalid_app_key" | "invalid_device_token" | "invalid_credentials" | "mfa_factor_required" | "email_taken";
                /** @description For people. Never parse it; branch on `code`. */
                message: string;
                /** @description The request field that caused the error. */
                param?: string;
                /** Format: uri */
                doc_url: string;
                /** @description The x-request-id of the request; quote it when reporting a problem. */
                request_id: string | null;
                /** @description Extra data for the code; its shape per code is in ErrorDetailsByCode. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Each error code's `details` shape, keyed by code. A code that isn't listed has no fixed shape. */
        ErrorDetailsByCode: {
            validation_failed: {
                fields: {
                    param: string;
                    message: string;
                }[];
            };
            service_unavailable?: {
                [key: string]: "up" | "down";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ProductsController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Text search over name, SKU, and barcode */
                q?: string;
                /** @description Filter to products in this category */
                categoryId?: number;
                /** @description Filter to products of this brand */
                brandId?: number;
                /** @description Minimum variant price, in cents */
                minPriceCents?: number;
                /** @description Maximum variant price, in cents */
                maxPriceCents?: number;
                /** @description Only include products with at least one variant in stock */
                inStock?: boolean;
                sortBy?: "price" | "newest" | "name";
                sortDir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProducts"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CategoriesController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategories"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CategoriesController_findOne: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Text search over name, SKU, and barcode */
                q?: string;
                /** @description Filter to products in this category */
                categoryId?: number;
                /** @description Filter to products of this brand */
                brandId?: number;
                /** @description Minimum variant price, in cents */
                minPriceCents?: number;
                /** @description Maximum variant price, in cents */
                maxPriceCents?: number;
                /** @description Only include products with at least one variant in stock */
                inStock?: boolean;
                sortBy?: "price" | "newest" | "name";
                sortDir?: "asc" | "desc";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    BrandsController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBrands"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    BrandsController_findOne: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Text search over name, SKU, and barcode */
                q?: string;
                /** @description Filter to products in this category */
                categoryId?: number;
                /** @description Filter to products of this brand */
                brandId?: number;
                /** @description Minimum variant price, in cents */
                minPriceCents?: number;
                /** @description Maximum variant price, in cents */
                maxPriceCents?: number;
                /** @description Only include products with at least one variant in stock */
                inStock?: boolean;
                sortBy?: "price" | "newest" | "name";
                sortDir?: "asc" | "desc";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CartController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CartController_getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CartController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CartController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CartController_updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CheckoutController_getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CheckoutController_createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CheckoutController_getShippingOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetShippingOptionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShippingOptionsResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CheckoutController_getSessionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CustomerController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CustomerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CustomerOrdersController_findAll: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCustomerOrders"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CustomerOrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOrderDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSignUpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_signin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
